hostname: kubernetes
fqdn: k8s.appkins.net
users:
  - name: terraform
    gecos: Terraform Provisioner
    primary_group: users
    shell: /bin/bash
    groups: users, admin
    ssh_import_id:
    - gh:appkins
    expiredate: '2024-12-24'
    lock_passwd: false
    sudo:  ALL=(ALL) NOPASSWD:ALL
    passwd: testpass

bootcmd:
  - systemctl disable --now systemd-networkd-wait-online
ntp:
  enabled: true
  servers:
    - ${NTP1}
    - ${NTP2}
manage_resolv_conf: true
network:
 version: 2
 ethernets:
   eno1:
     dhcp4: true
resolv_conf:
  nameservers: ['${DNS1}', '${DNS2}']
  searchdomains:
    - ${DOMAIN}
  domain: ${DOMAIN}
  options:
    rotate: true
    timeout: 1
apt_update: true
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1
  - path: /etc/modules-load.d/crio.conf
    content: |
      overlay
      br_netfilter
  - path: /etc/sysctl.d/99-kubernetes-cri.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1
  - path: /var/tmp/configfile.yaml
    content: |
      apiVersion: kubeadm.k8s.io/v1beta3
      clusterName: cluster1
      kind: ClusterConfiguration
      kubernetesVersion: 1.24.4
      networking:
        podSubnet: "${PODCIDR}"
      ---
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: InitConfiguration
      skipPhases:
        - addon/kube-proxy
apt:
  sources:
    cri-o:
      source: "deb [signed-by=$KEY_FILE] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /"
      keyid: "Release"
      keyserver: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04"
packages:
  - [kubelet, kubeadm, kubectl]
  - [cri-o, cri-o-runc]
package_update: true
package_upgrade: true
package_reboot_if_required: true
