apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wildcard-mydomain-com
  namespace: default
spec:
  secretName: wildcard-mydomain-com
  issuerRef:
    name: letsencrypt-prod-wildcard
    kind: Issuer
  commonName: '*.play.mydomain.com'
  dnsNames:
  - "*.play.mydomain.com"
  acme:
    config:
    - dns01:
        provider: cf-dns
      domains:
      - '*.play.mydomain.com'
      - play.mydomain.com
