apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
  - token: ${bootstrap_token}
    description: "kubeadm bootstrap token"
    ttl: "24h"
  - token: ${admin_token}
    description: "admin token"
    usages:
      - authentication
      - signing
    groups:
      - system:bootstrappers:kubeadm:default-node-token
nodeRegistration:
  name: "system-1"
  criSocket: unix:///var/run/containerd/containerd.sock
  taints: null
  kubeletExtraArgs:
    v: 4
  ignorePreflightErrors:
    - IsPrivilegedUser
  imagePullPolicy: IfNotPresent
localAPIEndpoint:
  advertiseAddress: "10.100.0.1"
  bindPort: 6443
certificateKey: "e6a2eb8581237ab72a4f494f30285ec12a9694d750b9785706a83bfcbbbd2204"
skipPhases:
  - addon/kube-proxy
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
etcd:
  # one of local or external
  local:
    imageRepository: "registry.k8s.io"
    imageTag: "3.2.24"
    dataDir: "/var/lib/etcd"
    extraArgs:
      listen-client-urls: "http://10.100.0.1:2379"
    serverCertSANs:
      -  "${id}.${domain}"
    peerCertSANs:
      - "10.100.0.1"
  # external:
    # endpoints:
    # - "10.100.0.1:2379"
    # - "10.100.0.2:2379"
    # caFile: "/etcd/kubernetes/pki/etcd/etcd-ca.crt"
    # certFile: "/etcd/kubernetes/pki/etcd/etcd.crt"
    # keyFile: "/etcd/kubernetes/pki/etcd/etcd.key"
networking:
  serviceSubnet: "10.96.0.0/16"
  podSubnet: ${pod_subnet}
  dnsDomain: "cluster.local"
kubernetesVersion: "v1.21.0"
controlPlaneEndpoint: "10.100.0.1:6443"
apiServer:
  extraArgs:
    authorization-mode: "Node,RBAC"
%{ if extra_volumes != null ~}
  extraVolumes:
%{ for name, path in extra_volumes ~}
    - name: ${name}
      hostPath: ${path}
      mountPath: ${path}
      readOnly: false
      pathType: File
%{ endfor ~}
%{ endif ~}
  certSANs:
    - "10.100.1.1"
    - "${id}.${domain}"
  timeoutForControlPlane: 4m0s
controllerManager:
  extraArgs:
    "node-cidr-mask-size": "20"
%{ if extra_volumes != null ~}
  extraVolumes:
%{ for name, path in extra_volumes ~}
    - name: ${name}
      hostPath: ${path}
      mountPath: ${path}
      readOnly: false
      pathType: File
%{ endfor ~}
%{ endif ~}
scheduler:
  extraArgs:
    address: "10.100.0.1"
%{ if extra_volumes != null ~}
  extraVolumes:
%{ for name, path in extra_volumes ~}
    - name: ${name}
      hostPath: ${path}
      mountPath: ${path}
      readOnly: false
      pathType: File
%{ endfor ~}
%{ endif ~}
certificatesDir: /etc/kubernetes/pki
imageRepository: "registry.k8s.io"
clusterName: ${id}
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
# kubelet specific options here
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
# kube-proxy specific options here
