apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: default
spec:
  cidrs:
  - cidr: "172.18.255.200/26"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: 01-bgp-peering-policy
spec: # CiliumBGPPeeringPolicySpec
  nodeSelector:
    matchExpressions:
    - {key: somekey, operator: NotIn, values: ['never-used-value']}
  virtualRouters: # []CiliumBGPVirtualRouter
  - localASN: 64512
    exportPodCIDR: true
    neighbors: # []CiliumBGPNeighbor
    - peerAddress: '10.0.0.1'
      peerASN: 64512
    serviceSelector:
      matchExpressions:
      - {key: somekey, operator: NotIn, values: ['never-used-value']}
