image:
	pullPolicy: IfNotPresent
ipam:
	mode: kubernetes
operator:
  replicas: 1
bgp:
  enabled: true
  announce:
    loadbalancerIP: true
    podCIDR: true
kubeProxyReplacement: strict
k8sServiceHost: kind-control-plane
k8sServicePort: 6443
ingressController:
  enabled: true
	loadbalancerMode: shared
